---
- name: Expose Docker metrics
  hosts: all
  tasks:
    - name: Copy daemon.json file
      ansible.builtin.copy:
        src: ../files/daemon.json
        dest: /etc/docker/
      notify:
        - restart docker

  handlers: 
    - name: restart docker
      ansible.builtin.service:
        name: docker.service
        state: restarted
