---
- name: Dockerized monitoring setup for Debian
  hosts: all
  roles:
    - role: docker_setup
    
    - role: prometheus_compose

    - role: grafana_compose
      when: inventory_hostname in groups['monitoring']
